name: 'Jest testing (including firestore rules)'
author: 'Bhekani Khumalo <bhekani@gmail.com>'
description: 'Run jest to test code, this includes the firebase firestore emulator to make it possible to also test firestore rules.'
branding:
  icon: 'airplay'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'